# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lPwE3sOSZEVoi-LPojyxd26Kx2bP9vj
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/ANKITA1.csv")
sns.histplot(data['mpg'],bins=10,color='blue',alpha=0.7)
plt.xlabel('mpg')
plt.ylabel('Frequency')
plt.title('Histogram of mpg')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/ANKITA1.csv")
sns.scatterplot(x='mpg',y='wt',data=data)
plt.xlabel('mpg')
plt.ylabel('frquency')
plt.title('scatter of mpg')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/ANKITA1.csv")
sns.barplot(x='model',y='mpg',data=data)
plt.xlabel('model')
plt.ylabel('Frequency')
plt.title('bar of mpg')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/ANKITA1.csv")
sns.boxplot(x='mpg',y='disp',data=data)
plt.xlabel('mpg')
plt.ylabel('Frequency')
plt.title('box of mpg')
plt.show()

import pandas as pd
data=pd.read_csv("/content/ANKITA1.csv")
print(data)